- name: Copy samba configuration
  template:
    src: smb.conf.j2
    dest: "/etc/samba/smb.conf"
  tags:
    - samba
    
- name: Create Samba restricted group
  group:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ samba_group }}"
  tags:
    - samba_group

- name: Add the User(s) to Samba group 
  user:
    name: "{{ item.name }}" 
    groups: "{{ item.group }}" 
    append: yes
  with_items: "{{ samba_users }}" 
  tags:
    - samba_users

- name: Create Samba Password for User(s)
  shell: "(echo {{ item.smbpasswd }}; echo {{ item.smbpasswd }}) | smbpasswd -s -a {{ item.name }}"
  with_items: "{{ samba_users }}"
  tags:
    - samba_users

- name: Delete samba user
  shell: "smbpasswd -x {{ item.name }}"
  with_items: "{{ delete_user }}"
  tags:
    - delete_user

- name: Delete user 
  shell: "deluser {{ item.name }}"
  with_items: "{{ delete_user }}"
  tags:
    - delete_user

- name: Cambio de permisos en carpeta 
  file: dest=/vencom/vencom/{{ item.name }} mode={{ item.rwx }} owner={{ item.user }} group={{ item.group }} state=directory recurse=yes
  with_items: "{{ permisos_cambio }}"
  tags:
    - permisos 

- name: Cambio de permisos en carpeta backup
  file: dest=/vencom/vencom_backup/{{ item.name }} mode={{ item.rwx }} owner={{ item.user }} group={{ item.group }} state=directory
  with_items: "{{ permisos_backup }}"
  tags:
    - permisos_backup 
